spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meteo?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # cria/atualiza as tabelas
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
        generate_statistics: false
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
server:
  port: 8090
auth:
  username: admin
  password: 123456